### ISSUE TITLE
Suppression d'un enseignement

### ISSUE THREAD

**Issue by camillou11** [FaouzyChaib/vtmiage#4]
Implémenter la suppression d'un enseignement.

**Comment by Desiderius77** [comment]
Pensez à la répercussion au niveau des séances : lorsqu'on supprime l'enseignement, il faut aussi supprimer les séances qui l'instancient

**Comment by JohnCarmack** [comment]
Oui monsieur, cela sera pris en compte.

**Comment by JohnCarmack** [comment]
La suppression d'un enseignement supprime les séances instanciées par celui-ci
